#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BindingEngine.Resource", IsApplication=false)]

namespace BindingEngine
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public static int apptheme_color = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public static int action_bar_back_margin_right = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int action_bar_height = 2131034112;
			
			// aapt resource value: 0x7f050002
			public static int action_bar_home_margin_left = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int action_bar_home_margin_right = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public static int pnet_action_bar_button_height = 2131034122;
			
			// aapt resource value: 0x7f050009
			public static int pnet_action_bar_button_width = 2131034121;
			
			// aapt resource value: 0x7f050006
			public static int pnet_action_bar_grid_padding = 2131034118;
			
			// aapt resource value: 0x7f050004
			public static int pnet_action_bar_height = 2131034116;
			
			// aapt resource value: 0x7f050008
			public static int pnet_action_bar_text_size = 2131034120;
			
			// aapt resource value: 0x7f050007
			public static int pnet_action_bar_title_height = 2131034119;
			
			// aapt resource value: 0x7f050005
			public static int pnet_action_image_size = 2131034117;
			
			// aapt resource value: 0x7f05000f
			public static int pnet_default_margin_bottom = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public static int pnet_default_margin_left = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public static int pnet_default_margin_right = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public static int pnet_default_margin_top = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public static int pnet_default_text_size = 2131034123;
			
			// aapt resource value: 0x7f050010
			public static int pnet_list_item_button_height = 2131034128;
			
			// aapt resource value: 0x7f050011
			public static int pnet_list_item_button_width = 2131034129;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int apptheme_btn_radio_holo_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int apptheme_btn_radio_off_disabled_focused_holo_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int apptheme_btn_radio_off_disabled_holo_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int apptheme_btn_radio_off_focused_holo_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int apptheme_btn_radio_off_holo_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int apptheme_btn_radio_off_pressed_holo_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int apptheme_btn_radio_on_disabled_focused_holo_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int apptheme_btn_radio_on_disabled_holo_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int apptheme_btn_radio_on_focused_holo_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int apptheme_btn_radio_on_holo_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int apptheme_btn_radio_on_pressed_holo_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int apptheme_btn_toggle_holo_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int apptheme_btn_toggle_off_disabled_focused_holo_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int apptheme_btn_toggle_off_disabled_holo_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int apptheme_btn_toggle_off_focused_holo_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int apptheme_btn_toggle_off_normal_holo_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int apptheme_btn_toggle_off_pressed_holo_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int apptheme_btn_toggle_on_disabled_focused_holo_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int apptheme_btn_toggle_on_disabled_holo_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int apptheme_btn_toggle_on_focused_holo_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int apptheme_btn_toggle_on_normal_holo_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int apptheme_btn_toggle_on_pressed_holo_dark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int apptheme_scrubber_control_disabled_holo = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int apptheme_scrubber_control_focused_holo = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int apptheme_scrubber_control_normal_holo = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int apptheme_scrubber_control_pressed_holo = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int apptheme_scrubber_control_selector_holo_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public static int apptheme_scrubber_primary_holo = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public static int apptheme_scrubber_progress_horizontal_holo_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public static int apptheme_scrubber_secondary_holo = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public static int apptheme_scrubber_track_holo_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public static int pnet_input = 2130837535;
			
			// aapt resource value: 0x7f020020
			public static int pnet_input_focused = 2130837536;
			
			// aapt resource value: 0x7f020021
			public static int pnet_input_normal = 2130837537;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080008
			public static int alert_button_panel = 2131230728;
			
			// aapt resource value: 0x7f080006
			public static int alert_message = 2131230726;
			
			// aapt resource value: 0x7f080007
			public static int alert_questionanswer_panel = 2131230727;
			
			// aapt resource value: 0x7f080005
			public static int alert_root_linear = 2131230725;
			
			// aapt resource value: 0x7f080001
			public static int pnetactionbar_actionbar_grid = 2131230721;
			
			// aapt resource value: 0x7f080000
			public static int pnetactionbar_root_scrollview = 2131230720;
			
			// aapt resource value: 0x7f080003
			public static int pnetactionbarbutton_button_imageview = 2131230723;
			
			// aapt resource value: 0x7f080004
			public static int pnetactionbarbutton_name_textview = 2131230724;
			
			// aapt resource value: 0x7f080002
			public static int pnetactionbarbutton_root_relative = 2131230722;
			
			// aapt resource value: 0x7f08000a
			public static int pnetbasiclist_list_listview = 2131230730;
			
			// aapt resource value: 0x7f080009
			public static int pnetbasiclist_root_relative = 2131230729;
			
			// aapt resource value: 0x7f08000c
			public static int pnetbasiclistviewheader_key_textview = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public static int pnetbasiclistviewheader_root_linear = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public static int pnetbasiclistviewheader_value_textview = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public static int pnetbasiclistviewitem_key_textview = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public static int pnetbasiclistviewitem_root_linear = 2131230734;
			
			// aapt resource value: 0x7f080010
			public static int pnetbasiclistviewitem_value_textview = 2131230736;
			
			// aapt resource value: 0x7f08001a
			public static int pnetpage_acceptbutton_pnetactionbarbutton = 2131230746;
			
			// aapt resource value: 0x7f080018
			public static int pnetpage_actionbar_linear = 2131230744;
			
			// aapt resource value: 0x7f080019
			public static int pnetpage_actionbar_pnetactionbar = 2131230745;
			
			// aapt resource value: 0x7f080015
			public static int pnetpage_backbutton_imagebutton = 2131230741;
			
			// aapt resource value: 0x7f080017
			public static int pnetpage_clientarea_frame = 2131230743;
			
			// aapt resource value: 0x7f080013
			public static int pnetpage_homebutton_imagebutton = 2131230739;
			
			// aapt resource value: 0x7f080011
			public static int pnetpage_root_relative = 2131230737;
			
			// aapt resource value: 0x7f080016
			public static int pnetpage_subtitle_textview = 2131230742;
			
			// aapt resource value: 0x7f080012
			public static int pnetpage_titlebar_linear = 2131230738;
			
			// aapt resource value: 0x7f080014
			public static int pnetpage_titletext_textview = 2131230740;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int PNetActionBar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int PNetActionBarButton = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int PNetAlertDialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int PNetBasicListView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int PNetBasicListViewHeader = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int PNetBasicListViewItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int PNetPage = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public static int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public static int Hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060008
			public static int AppTheme = 2131099656;
			
			// aapt resource value: 0x7f060001
			public static int PNetLargeBlueText = 2131099649;
			
			// aapt resource value: 0x7f060000
			public static int PNetMediumBlueText = 2131099648;
			
			// aapt resource value: 0x7f060005
			public static int SeekBarAppTheme = 2131099653;
			
			// aapt resource value: 0x7f060006
			public static int ToggleAppTheme = 2131099654;
			
			// aapt resource value: 0x7f060007
			public static int btnDarkBackground = 2131099655;
			
			// aapt resource value: 0x7f060002
			public static int editTextbgDark = 2131099650;
			
			// aapt resource value: 0x7f060004
			public static int editTextbgDarklarge = 2131099652;
			
			// aapt resource value: 0x7f060003
			public static int editTextbgDarkmedium = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
